package com.androiddevs.mvvmnewsapp.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Represents a single news article.
 * This class is used as a data model for the API response and as a Room database entity.
 * @param tableName Specifies the name of the table in the database.
 */
@Entity(
    tableName = "articles"
)
data class Article(

    // The primary key for the database table, auto-generated by Room.
    @PrimaryKey(autoGenerate = true)
    var id: Int? = null,

    val author: String?,
    val content: String?,
    val description: String?,
    val publishedAt: String?,
    val source: Source?, // Room requires a TypeConverter for this custom object.
    val title: String?,
    val url: String?,
    val urlToImage: String?
) : Serializable // Allows this object to be passed between components (e.g., fragments).
// TODO: Consider using Parcelable for better performance on Android.